### ISSUE TITLE
Missing ITU contry codes

### ISSUE THREAD

**Issue by pbilke** [musalbas/mcc-mnc-table#12]
330|816|11|287|pr|Puerto Rico||Puerto Rico Telephone Company Inc. (PRTC)
330|816|110|272|pr|Puerto Rico||Puerto Rico Telephone Company Inc. (PRTC)
376|886|050|80|tc|Turks and Caicos Islands||Digicel TCI Ltd
376|886|350|848|tc|Turks and Caicos Islands||Cable & Wireless (TCI) Ltd
376|886|352|850|tc|Turks and Caicos Islands||IslandCom Communications Ltd.
553|1363|01|31|tv|Tuvalu||Tuvalu Telecommunication Corporation (TTC)
659|1625|02|47|ss|South Sudan (Republic of)||MTN South Sudan (South Sudan
659|1625|03|63|ss|South Sudan (Republic of)||Gemtel Ltd (South Sudan
659|1625|04|79|ss|South Sudan (Republic of)||Network of The World Ltd (NOW) (South Sudan
659|1625|06|111|ss|South Sudan (Republic of)||Zain South Sudan (South Sudan

**Comment by musalbas** [comment]
Please read the contributing section of the readme.
