### ISSUE TITLE
There ara missing values

### ISSUE THREAD

**Issue by bananarachel** [musalbas/mcc-mnc-table#13]
For example , we can't find China Tietong(46003), or China Telecom (46011)
In fact, a lot of missing value can be found in 
https://en.wikipedia.org/wiki/Mobile_country_code
Just combined it with your file
[mcc-mnc.zip](https://github.com/musalbas/mcc-mnc-table/files/410963/mcc-mnc.zip)

**Comment by musalbas** [comment]
Please read the readme. This repo is not an original data source.
