### ISSUE TITLE
mcc-mnc.com poorly maintained, please manually add updates

### ISSUE THREAD

**Issue by E3V3A** [musalbas/mcc-mnc-table#17]
It seem that the website you use to pull info is rather poorly maintained. Manual updates through PRs may be a good option to keep up to date. 

E.g. For Lithuania,
`Omnitel` is now `Telia`, and `Tele2` is `Vodaphone`.

**Comment by musalbas** [comment]
Feel free to start your own repository with manually maintained information, but I'm too lazy and don't have the incentive to take on such a commitment.

**Comment by E3V3A** [comment]
@musalbas Sorry, if that sounded bad. It's not what I meant. What I meant was that, since it seem that quite a bunch of people are using your repo, that you could allow people to make a PR with the updates and all you'd have to do is click a button to accept. Is that still too much to ask?

**Comment by musalbas** [comment]
The repository is automatically updated from the website daily using a script, so if someone submits a change, it will be overwritten anyway, unless I want to manually resolve conflicts if the website also updates the same value, which I don't.

**Comment by E3V3A** [comment]
ok, got it.
