### ISSUE TITLE
Table not updated

### ISSUE THREAD

**Issue by JackPGreen** [musalbas/mcc-mnc-table#18]
Hi,

Firstly - thanks for making this library and saving me doing the same thing.

The table has not been updated since 20/12/2017.

Just thought I'd let you know in case it's a bug.

Regards,
Jack.

**Comment by al3xmore** [comment]
Hi Italy Hi3G is wrong.
Name is H3g (Hi3g is in nordic european country)

**Comment by JackPGreen** [comment]
For issues with network names, see https://github.com/musalbas/mcc-mnc-table/issues/15

**Comment by musalbas** [comment]
The table is pulled from http://mcc-mnc.com/.
