### ISSUE TITLE
Convert Operator Name to Operator Code

### ISSUE THREAD

**Issue by telecomsxchange** [musalbas/mcc-mnc-table#19]
Thanks for building this, however there is one issue, we need to get the CC + Network Code instead of name. basically we want to be able to show the real Network area code instead of the network name. 

for example instead of:

MCC	MCC (int)	MNC	MNC (int)	ISO	Country	Country Code	Network
289 	649		         68             1679	          ge	   UAE              971                Etisalat      

Show this
MCC	MCC (int)	MNC	MNC (int)	ISO	Country	**Country Code**	**Network**
289 	649		         68             1679	          ge	   UAE              971                      59

**Comment by tkojemile** [comment]
Mnc is not int. It can have 0 prefix

**Comment by musalbas** [comment]
The table is pulled from http://mcc-mnc.com/, I have no control over its contents.
