### ISSUE TITLE
About French Guiana ISO

### ISSUE THREAD

**Issue by paintthetiger** [musalbas/mcc-mnc-table#21]
Hi, 
Firstly, I really appreciate about codes and tables.
But I found some wrong information in tables. 
While I'm using mcc-mnc table files, I found some wrong data about French Guiana ISO.

Actually, the ISO code of French Guiana ISO is 'gf'. (https://en.wikipedia.org/wiki/ISO_3166-2:GF)
But, in http://mcc-mnc.com/, it is written as 'fg'. So, it is all same in all tables.

Though it is basically the problem of  http://mcc-mnc.com/, I want to discuss about handling in code level.

Thanks 🙂

**Comment by musalbas** [comment]
Thanks for this, however maintaining the information here (including at a code level) is not a commitment I'm willing to take on at this time; mcc-mnc.com should fix this. The data import is provided as-is.
