### ISSUE TITLE
Missing some Network operators

### ISSUE THREAD

**Issue by stevemcmillen** [musalbas/mcc-mnc-table#4]
I was looking over your MNC/MCC list and tought you would like to know that it seems to be missing a few Network names.  The ones missing are listed below with values I found from Wikipedia and one other site.  They differ in some cases so I'm providing two columns from each site.

MCC    MNC    ISO    Country Code    Country    Network(wikipedia)    Netowork (http://mcclist.com/mobile-network-codes-country-codes.asp)
238    7    dk    45    Denmark    Mundio Mobile    Mundio Mobile
340    10    gp    590    Guadeloupe    Guadeloupe Téléphone Mobil    #N/A
310    50    us    1    United States    ACS Wireless Inc.    #N/A
310    880    us    1    United States    Advantage Cellular Systems, Inc.    DTC Wireless
310    640    us    1    United States    Airadigm Communications    AirFire
311    130    us    1    United States    Alltel    <no value>
311    190    us    1    United States    #N/A    <no value>
310    30    us    1    United States    Centennial Communications    AT&T
310    630    us    1    United States    Choice Wireless    AmeriLink PCS
311    40    us    1    United States    Commnet Wireless    <no value>
312    380    us    1    United States    #N/A    #N/A
310    930    us    1    United States    Copper Valley Wireless    #N/A
311    240    us    1    United States    #N/A    #N/A
310    80    us    1    United States    Corr Wireless Communications LLC    Corr
311    520    us    1    United States    #N/A    #N/A
311    210    us    1    United States    Farmers Cellular Telephone    <no value>
310    970    us    1    United States    Globalstar USA    Globalstar
311    30    us    1    United States    Indigo Wireless   
311    90    us    1    United States    Long Lines Wireless LLC    Long Lines Wireless
311    660    us    1    United States    #N/A    metroPCS
311    0    us    1    United States    Mid-Tex Cellular Ltd.    <no value>
311    380    us    1    United States    #N/A    #N/A
311    100    us    1    United States    High Plains Wireless    <no value>
310    540    us    1    United States    Oklahoma Western Telephone Company    Oklahoma Western
311    80    us    1    United States    Pine Telephone Company    Pine Cellular
310    790    us    1    United States    PinPoint Communications Inc.    PinPoint
311    730    us    1    United States    #N/A    #N/A
311    540    us    1    United States    #N/A    #N/A
311    910    us    1    United States    #N/A    #N/A
311    740    us    1    United States    #N/A    #N/A
311    150    us    1    United States    Wilkes Cellular    <no value>

**Comment by musalbas** [comment]
The list is automatically pulled from http://mcc-mnc.com/. This isn't a self-maintained list.
