### ISSUE TITLE
Tables are incomplete, many new networks should be added.

### ISSUE THREAD

**Issue by tonywyant** [musalbas/mcc-mnc-table#9]
Recent document, available from ITU has more complete mnc mcc listings. Some, or all of this, information should be added to the mnc mcc tables:

     https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.212B-2015-PDF-E.pdf

There are other sources of more up to date information (including wikipedia)

**Comment by musalbas** [comment]
Tell http://mcc-mnc.com/. They provide the data. I just format it into CSV and other formats.

Feel free to submit a pull request for a script that uses a different source of data.
